ericniebler/stl2

concepts.tex, iterators.tex
Convert compound-requirements that introduce only an expression constraint into equivalent simple-requirements. C++ has enough curly braces as it is, we don't need to add them in places where they have no effect ;)
=> Simplify concept definitions:

Makefile
The bibliography isn't being pulled into DXXXX correctly because the Makefile is still trying to `bibtex N4382` instead of `bibtex DXXXX`.
=> Fix bibliography generation

iterators.tex
=> IndirectlySwappable relates the *reference* types of two Readables

iterators.tex
=> Use "iff" instead of "only if" for dereferenceability of Bidi iterators

ext/proxy/Dxxxx.md
I thought I had committed these changes to the first PR but in fact I hadn't. Sorry.
=> actually remove equality-preserving requirement on iter_move

concepts.tex, decomposition.tex, deprecated.tex
* concepts.tex: Some `Convertible@\newtxt{To}@` occurrences
* decomposition.tex, deprecated.tex: cleanup what little markup they have.
=> Cleanup a few more bits of markup

algorithms.tex, concepts.tex, decomposition.tex, deprecated.tex, iterators.tex
Fixes #173.
Don't merge this until after (1) merging Chris's markup cleanup of iterators.tex, and (2) correcting the resulting merge conflicts.
=> Use "Effects: Equivalent to" to specify distance in [ranges.primitives]

utilities.tex
Part of the ranges telecon 3 feedback is to avoid duplication of the make_pair/tuple verbiage in make_tagged_pair/tuple. How's this?
=> respecify make_tagged_(pair|tuple) in terms of make_$1

concepts.tex, iterators.tex
- The standard doesn't describe. It *specifies*.
- Replace "comparable for equality" with "satisfy EqualityComparable" in description (specification) of InputIterator.
=> describes->specifies, more changes from ranges telecon 3

concepts.tex, future.tex, iterators.tex, utilities.tex
Remove reference to proxy iterators and common_type future work which is now integrated.
=> Editorial: \tcode section headers where missing.

concepts.tex
...and editorially correct "`x` is an equality preserving expression" to "`x()` is an equality preserving expression" for nullary function `x`.
=> Remove markup from concepts

algorithms.tex, compatibility.tex, concepts.tex, deprecated.tex, iterators.tex, lib-intro.tex
Since the term of art for these things is still "callable" in C++14 (and in C++17?), I am leaving the term "indirect callable" as the term of art, but only renaming the concepts themselves.
PR against master since this seems editorial to me.
=> Rename Callable concepts to Invocable concepts, fixes #254

iterators.tex
* Relocate introductory material from [iterators.counted] into [counted.iterator] to be consistent with more recent library wording style.
=> Front matter for [counted.iterator]

iterators.tex
* Retitle [iterators.move] as "Move iterators and sentinels."
* Split the front matter from [iterators.move] out into [move.iterator] and [move.sentinel].
=> Review: front matter for [move.sentinel]

acknowledgements.tex, compatibility.tex, intro.tex
Fixes #303.
Per ISO/IEC directives part 2 §10.6 "References in a document to itself":
> For an individual document, the form "this document" shall be used.
=> [Editorial] "This paper" => "This document"

ext/constructible/.gitignore, ext/constructible/constructible.md, ext/post_inc/post_inc.md
Fix the garbled sentence on line 59 (and autostrip trailing whitespace)
=> Editorial fixes to P0547

iterators.tex
This complicates the application of #284. Where does `iter_exchange` go? It can't go with `iter_move` and `iter_swap` since it isn't a customization point. And if `iter_swap` is specified in terms of `iter_exchange`, then it is making use of concepts that haven't been defined yet. Even so, I feel this is a (vast) improvement.
=> [EDITORIAL] major reorg of <iterator>; add concepts to the synopsis

ext/constructible/P0547.html, ext/constructible/constructible.md
Update the occurrences of the subsumption wording in P0547 in accordance with LWG Kona discussion. This agrees with the form of the amended wording of ready issue #321.
=> P0547 wording updates (per LWG Kona discussion)

ext/post_inc/post_inc.md
* Use decltype(auto) instead of "see below" in declarations
* Insert missing semicolons in the specification of counted_iterator::operator++
* Simplify counted_iterator::operator++(int) by using pre-increment in the effects-equivalent-to, which notably "inherits" the Requires element.
=> [EDITORIAL] LWG Kona changes:

intro.tex
Prevailing convention appears to be capitalizing only the first letter.
=> Fix capitalization in clause titles

concepts.tex, iterators.tex
Fixes #70, #229, #300, #301, #310, #313,  #339, #381, #382, #387, #399.
=> Apply P0547R2

iterators.tex
366: common_iterator::operator-> is underconstrained
368: common_iterator’s and counted_iterator’s const operator* need to be constrained
Fixes #366 and #368.
=> Apply P0740R0 PRs for:

ext/adaptors/ranges-lib.tex
also, ranges.adaptors.iota_view.comp => ranges.adaptors.iota_view.sentinel.cmp, to match the tag for iteraotr comparisons
=> Fix duplicate labels likely caused by c&p errors

ext/adaptors/macros.tex
=> Use \texorpdfstring in \xname to suppress hyperref warnings

ext/adaptors/ranges-lib.tex
All changes implemented on the subrange_cmc branch of cmcstl2.
* pair-like: ensure that `get<>()` works.
* pair-like-convertible-to:
* put `!Range<T>` first, because I'm paranoid about requirement recursion.
* Verify that the result of calling `get` on the actual expression type converts.
* pair-like-convertible-from:
* Ditto `!Range<T>` first
* Simplify by removing the `ConvertibleTo` constraints
* iterator-sentinel-pair:
* Ditto `!Range<T>` first
* Don't name the `subrange_kind` template parameter "Sized" to avoid confusion. Let's use `K`, and replace all of the `B` parameter names with `K`.
* Don't allow `subrange_kind::unsized` when `SizedSentinel<S, I>` holds; it's not needed.
* Fix the last vestiges of the change from `bool` to `subrange_kind`, including using `K == …
=> detailed subrange review:

ext/adaptors/ranges-lib.tex
* add `is_class_v` constraint
* `s/The view_interface/The class template view_interface/`
* Don't use a trailing-requires-clause for template `data`
The `is_class_v` constraint borders on a design change, but I think we can call it a wording fix to realize the intended design with a straight face and skip LEWG.
=> minor view_interface tweaks

ext/merge2std2/iterators.tex, ext/merge2std2/ranges-lib.tex
* variadic instead of single-function-type parameter
* require the `Is...` to be `Readable` before using `reference_t` on them
=> [P0896] indirect_result fixes
