ericniebler/stl2

- utilities.tex
Fixes #40. (Aside: If we decide to decompose Semiregular into Movable and Copyable, Movable is a fairly tight fit for swap & exchange).
> swap and exchange require Destructible

- iterators.tex
> Change "Concept WeakIterators" title to be singular

- iterators.tex
There's no PDF in this pull request, to avoid merge conflicts.
> Insert iterators satisfy WeakOutputIterator. Fixes caseycarter/stl2#16

- algorithms.tex
> [Editorial] Correct text of [algorithms.general]/15

- ext/writable/.gitignore
- ext/writable/D0441R0.html
- ext/writable/Makefile
- ext/writable/P0441.md
- ext/writable/acm-sig-proceedings.csl
- ext/writable/header.html.in
- ext/writable/notes.md
- ext/writable/pandoc-template.html
I still need to clean this up, figured I may as well solicit some feedback while I'm at it.
> First draft of P0441 Merge Writable and MoveWritable

- concepts.tex
- decomposition.tex
- iterators.tex
- numerics.tex
> Replace 'requires (' with 'requires('

- ext/writable/D0441R0.html
- ext/writable/P0441.md
- iterators.tex
> Cleanup and integration of P0441

- iterators.tex
> integrate Jacksonville review feedback

- concepts.tex
> [Editorial] Strike "purely semantic" note about (Weakly)?EqualityComparable

- algorithms.tex
Diff is too large to view; I'll try to push smaller chunks hereafter to ease review.
> Remove markup from algorithms.tex

- deprecated.tex
> Annotate deprecation of rvalue range access.

- acknowledgements.tex
- algorithms.tex
- concepts.tex
- config.tex
- cover-wd.tex
- cxx.tex
- deprecated.tex
- front.tex
- intro.tex
- iterators.tex
- lib-intro.tex
- numerics.tex
- ranges.tex
- statements.tex
- tagged.tex
- utilities.tex
Removes erroneous diff markings
Renumber sections and tables
Fix up references to the IS
Remove unnecessary appendices
Add missing Library Intro and Utilities front matter
Assorted editorial fixes
> Make the Ranges TS a standalone document

- algorithms.tex
- concepts.tex
- iterators.tex
Merge the fixes that were approved in Issaquah but that didn't make it into the PDTS.
> Rebased issaquah issues processing

- algorithms.tex
- deprecated.tex
> PR for #359

- intro.tex
- iterators.tex
- macros.tex
- ranges.tex
Despite being editorial, this is probably interesting enough to merit more eyes than just mine.
> Define "projection"; Fixes #221.

- statements.tex
> Integrate C++17 FDIS wording for stmt.ranged with diff marks

- algorithms.tex
- cxx.tex
> [EDITORIAL] Clarify that alg.foreach has stronger requirements than in C++14

- intro.tex
> Bring [intro.defs] into compliance with ISO/IEC directive part section 16.5

- acknowledgements.tex
- compatibility.tex
- intro.tex
- ranges.bib
- sentrework.tex
> [EDITORIAL] N3351 and N4128 are non-normative references, move to bib

- algorithms.tex
- concepts.tex
- deprecated.tex
- files
- intro.tex
- iterators.tex
- lib-intro.tex
- numerics.tex
- ranges-lib.tex
- ranges.tex
- tags.files
- utilities.tex
~~Don't merge yet. There is a high likelihood that 830e9fd stomped some changes. I need to investigate.~~
OK, I fixed a bad table and reinstated 00d9f8d which got lost in the shuffle. I also fixed more occurrences of "an `Range`" as editorial. This is ready for its close-up.
> Switch to variable concepts, and other things

- concepts.tex
> Apply the PR of #167 from P0740R0

- algorithms.tex
> Apply P0663R0 PR for  316: copy_if “Returns” clause incorrect

- statements.tex
> Apply P0662R0: Update ranged-for-loop wording

- algorithms.tex
> Apply P0740R0 PR for 170: unique_copy and LWG 2439

- algorithms.tex
> Apply P0740R0 PR for 176: Relax requirements on replace and replace_if

- iterators.tex
- ranges-lib.tex
- utilities.tex
> Apply P0579R1: Constexpr for <experimental/ranges/iterator>

- algorithms.tex
- iterators.tex
> Apply P0740R0 PR for 289: [iterator, count) ranges

- lib-intro.tex
> Apply P0740R0 PR for 404: Normative content in informative subclause

- iterators.tex
> Apply P0740R0 PR for 407: istreambuf_iterator::operator->

- iterators.tex
> Apply P0740R0 PR for 424: Constrain return types in IndirectInvocable

- cxx.tex
- tables.tex
- utilities.tex
> Assorted common_type and common_reference fixes

- iterators.tex
> Apply P0663R0 PR for 331: Reorder requirements in concept Iterator

- numerics.tex
> [EDITORIAL] Don't redundantly wrap URNG in namespaces

- ext/adaptors/intro.tex
- ext/adaptors/ranges-lib.tex
A series of changes from a partial review of D0789R1.
> View interface cmc

- ext/adaptors/ranges-lib.tex
This *was* part of my `view_interface` PR, until I rebased and squashed and lost this commit.
> view_interface::operator C constraints

- ext/adaptors/LEWG 20171107 feedback.md
- ext/adaptors/ranges-lib.tex
> LEWG review feedback for D0789R1

- ext/merge2std2/iterators.tex
- ext/merge2std2/ranges-lib.tex
Don't use "abbreviated function templates" since they are not in C++20.
> Fix iterator adaptor conversions:

- ext/adaptors/ranges-lib.tex
> [P789] Simplify constraints on view_interface::data

- ext/merge2std2/intro.tex
- ext/merge2std2/iterators.tex
- ext/merge2std2/ranges-lib.tex
@timsong-cpp I think this fixes a couple of issues you reported.
> P896 fixes
